spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurantdemoappdb
    username: postgres
    password: postgres
    sql-script-encoding: UTF-8
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Hibernate ddl auto (create, create-drop, validate, update)
  #spring.jpa.properties.hibernate.show_sql=true
  #spring.jpa.properties.hibernate.use_sql_comments=true
  #spring.jpa.properties.hibernate.format_sql=true
server:
  port: 80
