spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurantdemoappdb
    username: postgres
    password: postgres
    sql-script-encoding: UTF-8
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    open-in-view: false
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello


    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Hibernate ddl auto (create, create-drop, validate, update)
  #spring.jpa.properties.hibernate.show_sql=true
  #spring.jpa.properties.hibernate.use_sql_comments=true
  #spring.jpa.properties.hibernate.format_sql=true
server:
  port: 8085



confirmationtoken:
  expireDuration: 15

email:
  confirmation-link: http://localhost:8080/api/v1/registration/confirm?token=
